name: build release
on: [push]

jobs:
  build-release:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    name: cargo build
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: "release-lto"
      - run: cargo build --profile=release-lto
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: target/release-lto/esdump-rs*
          retention-days: 1
