name: build release
on: [push]

jobs:
  build-release:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    name: cargo build
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --profile=release-lto
