name: Build and publish release
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build_release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            bin: esdump-rs
            target: x86_64-unknown-linux-gnu
            suffix: tar.gz
          - os: macOS-latest
            bin: esdump-rs
            target: aarch64-apple-darwin
            suffix: tar.gz
          - os: windows-latest
            bin: esdump-rs.exe
            target: x86_64-pc-windows-msvc
            suffix: zip
    name: cargo build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: "release-lto"
      - run: cargo build --target=${{ matrix.target }} --profile=release-lto
      - run: |
          cp target/${{ matrix.target }}/release-lto/${{ matrix.bin }} ${{ matrix.bin }}
           
          if [[ "${{ matrix.os }}" == "windows-latest" ]]
          then
          7z a ${{ matrix.target}}.${{ matrix.suffix }} ${{ matrix.bin }} 
          else
          tar czvf ${{ matrix.target}}.${{ matrix.suffix }} ${{ matrix.bin }} 
          fi
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target}}.${{ matrix.suffix }}
          path: ${{ matrix.target}}.${{ matrix.suffix }}
          retention-days: 1

  create_release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build_release

    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: |
            **/*.tar.gz
            **/*.zip
