name: Integration test
on: [push]

jobs:
  integration-test:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: "test"

      - uses: hoverkraft-tech/compose-action@v0.0.0

      - name: Seed ES
        run: cargo run -p seed-es-data http://localhost:9201 test-index

      - name: Seed OS
        run: cargo run -p seed-es-data http://localhost:9202 test-index

      - name: Dump ES
        run: |
          cargo run http://localhost:9201 --index=test-index --batches-per-file=5 --batch-size=5000 s3://es-dump/es/ --env-file=test.env --concurrency=10

      - name: Dump OS
        run: |
          cargo run http://localhost:9202 --index=test-index --batches-per-file=5 --batch-size=5000 s3://es-dump/es/ --env-file=test.env --concurrency=10

#      - run: cargo build --profile=release-lto
#      - name: Upload build artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{ matrix.platform }}
#          path: target/release-lto/esdump-rs*
#          retention-days: 1
